apiVersion: v1
kind: Service
metadata:
  name: {{ include "straight.fullname" . }}
  labels:
    {{- include "straight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "straight.selectorLabels" . | nindent 4 }}
